Fixing Multi OS Boot Problem

diff --git a/.github/workflows/daily-report.yml b/.github/workflows/daily-report.yml
--- a/.github/workflows/daily-report.yml
+++ b/.github/workflows/daily-report.yml
@@ -9,6 +9,10 @@ on:
     - cron: "0 3 * * *"
   workflow_dispatch:
 
+concurrency:
+  group: daily-report
+  cancel-in-progress: false
+
 jobs:
 
   docker-job:
@@ -19,16 +23,13 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Build Docker Image
-        run: |
-          docker build -t daily-report .
+        run: docker build -t daily-report .
 
       - name: Run inside container
-        run: |
-          docker run --name report-run daily-report
+        run: docker run --name report-run daily-report
 
       - name: Copy report from container
-        run: |
-          docker cp report-run:/app/reports ./reports
+        run: docker cp report-run:/app/reports ./reports
 
       - name: Upload Docker Report Artifact
         uses: actions/upload-artifact@v4
@@ -36,13 +37,10 @@ jobs:
           name: docker-report
           path: reports/
 
+
   build:
-
-    strategy:
-      matrix:
-        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-latest]
-
-    runs-on: ${{ matrix.os }}
+    runs-on: ubuntu-latest
+    needs: docker-job
 
     steps:
       - name: Checkout repo
@@ -59,15 +57,15 @@ jobs:
           git config user.name "github-actions[bot]"
           git config user.email "github-actions[bot]@users.noreply.github.com"
           git add reports/
-          git commit -m "Daily report ($(date)) - ${{ matrix.os }}" || echo "No changes"
+          git commit -m "Daily report ($(date))" || echo "No changes"
 
       - name: Create GitHub Issue if problem found
         run: |
           if grep -qi "error" reports/latest_report.txt; then
-            echo "⚠ Error found — creating a GitHub issue..."
+            echo "⚠ Error found — creating GitHub issue..."
             GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} script/create_issue.sh
           else
-            echo "No errors found - skipping issue creation."
+            echo "No errors found — skipping issue creation."
           fi
 
       - name: Push changes
@@ -76,7 +74,7 @@ jobs:
       - name: Upload Report as Artifact
         uses: actions/upload-artifact@v4
         with:
-          name: system-report-${{ matrix.os }}
+          name: system-report
           path: reports/*.txt
 
       - name: List repo files
@@ -96,7 +94,3 @@ jobs:
             \"text\": \"*DevOps Automation Report*\nStatus: $STATUS\nRepository: ${{ github.repository }}\nWorkflow: ${{ github.workflow }}\nRun ID: ${{ github.run_id }}\nTriggered at: $(date)\"
           }" \
           ${{ secrets.SLACK_WEBHOOK_URL }}
-
-    concurrency:
-      group: daily-report-${{ matrix.os }}
-      cancel-in-progress: false
