a simple index

diff --git a/.github/workflows/daily-report.yml b/.github/workflows/daily-report.yml
--- a/.github/workflows/daily-report.yml
+++ b/.github/workflows/daily-report.yml
@@ -1,11 +1,12 @@
 name: Daily System Report (Build & Push Docker)
 
 permissions:
-  contents: write
+  contents: write # Needed for git push
+  issues: write  # If you add issue creation later
 
 on:
   schedule:
-    - cron: "0 03 * * *"   # Run daily at 03:00 UTC
+    - cron: "0 03 * * *"   # Run daily at 03:00 UTC (8:39 AM IST  )
   workflow_dispatch:
 
 concurrency:
@@ -62,6 +63,17 @@ jobs:
   # ------------------------------
   # CREATE ISSUE ON FAILURE
   # ------------------------------
+      - name: Notify Docker Push Completed (Telegram)
+        run: |
+          MSG:"🐳 *Docker Push Successful!*\nImage: ${{ secrets.DOCKER_USERNAME }}/devops-daily-report\nTag: ${{ env.IMAGE_TAG }}"
+          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
+            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
+            -d parse_mode="Markdown" \
+            -d text="$MSG"
+
+  # ------------------------------
+  # CREATE ISSUE ON FAILURE
+  # ------------------------------
       - name: Create GitHub Issue on Failure
         if: failure()
         uses: peter-evans/create-issue-from-file@v4
@@ -86,6 +98,52 @@ jobs:
           attachments: ./reports/latest_report.txt
 
   # ----------------------------------------------------
+  # Docker Push Success Message
+  # ----------------------------------------------------
+
+      - name: Docker Push Success
+        run: |
+          MSG:"🐳 Docker Image Pushed Successfully\nRepository: ${{ secrets.DOCKER_USERNAME }}/devops-daily-report"
+          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
+            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
+            -d text="$MSG"
+
+  # ----------------------------------------------------
+  # JOB 3: Run Report Script + Commit Output
+  # ----------------------------------------------------
+  run-and-commit:
+    needs: push-docker
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Make Report Script Executable
+        run: chmod +x script/daily_report.sh
+
+      - name: Run Report Script
+        run: bash script/daily_report.sh
+
+      - name: Commit and Push Reports
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          git config user.name "github-actions[bot]"
+          git config user.email "github-actions[bot]@users.noreply.github.com"
+          git add reports/ || true
+          git commit -m "Daily Report: $(date +'%Y-%m-%d')" || echo "No changes to commit"
+          git push origin main
+
+      - name: Upload Report Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: system-report
+          path: reports/
+
+  # ----------------------------------------------------
   # SEND TELEGRAM MESSAGE (optional)
   # ----------------------------------------------------
       - name: Send Telegram Notification
@@ -99,17 +157,6 @@ jobs:
             -d parse_mode="Markdown" \
             -d text="${TEXT}"
 
-  # ----------------------------------------------------
-  # Docker Push Success Message
-  # ----------------------------------------------------
-
-      - name: Docker Push Success
-        run: |
-          MSG:"🐳 Docker Image Pushed Successfully\nRepository: ${{ secrets.DOCKER_USERNAME }}/devops-daily-report"
-          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
-            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
-            -d text="$MSG"
-    
   # ----------------------------------------------------
   # Workflow Failure Natification
   # ----------------------------------------------------
@@ -127,36 +174,3 @@ jobs:
                 -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
                 -d parse_mode=Markdown \
                 -d text="$MSG"
-
-  # ----------------------------------------------------
-  # JOB 3: Run Report Script + Commit Output
-  # ----------------------------------------------------
-  run-and-commit:
-    needs: push-docker
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
-
-      - name: Make Report Script Executable
-        run: chmod +x script/daily_report.sh
-
-      - name: Run Report Script
-        run: bash script/daily_report.sh
-
-      - name: Commit and Push Reports
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          git config user.name "github-actions[bot]"
-          git config user.email "github-actions[bot]@users.noreply.github.com"
-          git add reports/ || true
-          git commit -m "Daily Report: $(date +'%Y-%m-%d')" || echo "No changes"
-          git push origin main
-
-      - name: Upload Report Artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: system-report
-          path: reports/
