Activate Telegram Bot

diff --git a/.github/workflows/daily-report.yml b/.github/workflows/daily-report.yml
--- a/.github/workflows/daily-report.yml
+++ b/.github/workflows/daily-report.yml
@@ -1,59 +1,67 @@
 name: Daily System Report (Build & Push Docker)
 
+permissions:
+  contents: write
+
 on:
   schedule:
-    - cron: "30 3 * * *"   # 9:00 AM IST daily
+    - cron: "0 03 * * *"   # Run daily at 03:00 UTC
   workflow_dispatch:
-  push:
-    paths:
-      - "script/**"
-      - "docker/Dockerfile"
+
+concurrency:
+  group: daily-report
+  cancel-in-progress: false
 
 jobs:
+  # ----------------------------------------------------
+  # JOB 1: Build Image
+  # ----------------------------------------------------
+  docker-build:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4
 
-  build-and-push:
+      - name: Build Docker Image (CI Build)
+        run: docker build -t daily-report:ci .
+
+      - name: Inspect Image
+        run: docker images | grep daily-report
+
+  # ----------------------------------------------------
+  # JOB 2: Push Image to Docker Hub
+  # ----------------------------------------------------
+  push-docker:
+    needs: docker-build
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout repo
+      - name: Checkout Repository
         uses: actions/checkout@v4
 
-      # ------------------------------
-      # DOCKER LOGIN
-      # ------------------------------
       - name: Login to Docker Hub
         run: |
-          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | \
+          echo "${{ secrets.DOCKER_PASSWORD }}" |
           docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
-      # ------------------------------
-      # BUILD IMAGE
-      # ------------------------------
-      - name: Build Docker image
-        run: |
-          docker build -t daily-report:latest -f docker/Dockerfile .
+      - name: Build Image
+        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-daily-report:latest .
 
-      # ------------------------------
-      # TAG IMAGE
-      # ------------------------------
-      - name: Tag Docker images
+      - name: Tag with Timestamp
         run: |
-          TAG=$(date +'%Y%m%d%H%M')
-          echo "TAG=$TAG" >> $GITHUB_ENV
-          docker tag daily-report:latest ${{ secrets.DOCKER_USERNAME }}/daily-report:latest
-          docker tag daily-report:latest ${{ secrets.DOCKER_USERNAME }}/daily-report:$TAG
+          TAG=$(date +'%Y%m%d-%H%M%S')
+          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
+          docker tag ${{ secrets.DOCKER_USERNAME }}/devops-daily-report:latest \
+                     ${{ secrets.DOCKER_USERNAME }}/devops-daily-report:$TAG
 
-      # ------------------------------
-      # PUSH IMAGES
-      # ------------------------------
-      - name: Push Docker images
+      - name: Push Images
         run: |
-          docker push ${{ secrets.DOCKER_USERNAME }}/daily-report:latest
-          docker push ${{ secrets.DOCKER_USERNAME }}/daily-report:${TAG}
+          docker push ${{ secrets.DOCKER_USERNAME }}/devops-daily-report:latest
+          docker push ${{ secrets.DOCKER_USERNAME }}/devops-daily-report:${{ env.IMAGE_TAG }}
 
-      # ------------------------------
-      # CREATE ISSUE IF ERROR FOUND
-      # ------------------------------
+  # ------------------------------
+  # CREATE ISSUE ON FAILURE
+  # ------------------------------
       - name: Create GitHub Issue on Failure
         if: failure()
         uses: peter-evans/create-issue-from-file@v4
@@ -62,9 +70,9 @@ jobs:
           content-filepath: ./reports/latest_report.txt
           labels: error, automated
 
-      # ------------------------------
-      # SEND EMAIL (optional)
-      # ------------------------------
+  # ------------------------------
+  # SEND EMAIL (optional)
+  # ------------------------------
       - name: Send Report Email
         uses: dawidd6/action-send-mail@v3
         with:
@@ -77,30 +85,78 @@ jobs:
           from: "GitHub Actions Bot"
           attachments: ./reports/latest_report.txt
 
+  # ----------------------------------------------------
+  # SEND TELEGRAM MESSAGE (optional)
+  # ----------------------------------------------------
+      - name: Send Telegram Notification
+        if: always()
+        run: |
+          STATUS="${{ job.status }}"
+          TEXT="🔔 *DevOps Daily Report*\n\n*Status:* ${STATUS}\n*Repo:* ${{ github.repository }}\n*Run ID:* ${{ github.run_id }}"
+
+          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
+            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
+            -d parse_mode="Markdown" \
+            -d text="${TEXT}"
+
+  # ----------------------------------------------------
+  # Docker Push Success Message
+  # ----------------------------------------------------
+
+      - name: Docker Push Success
+        run: |
+          MSG:"🐳 Docker Image Pushed Successfully\nRepository: ${{ secrets.DOCKER_USERNAME }}/devops-daily-report"
+          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
+            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
+            -d text="$MSG"
+    
+  # ----------------------------------------------------
+  # Workflow Failure Natification
+  # ----------------------------------------------------
+
+      failure-notify:
+        needs: [docker-build, push-docker, run-and-commit]
+        runs-on: ubuntu-latest
+        if: failure()
+
+        steps:
+          - name: Send Failure Alert to Telegram
+            run: |
+              MSG="❌ *Workflow Failed!*\nRepository: ${{ github.repository }}\nRun ID: ${{ github.run_id }}"
+              curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
+                -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
+                -d parse_mode=Markdown \
+                -d text="$MSG"
+
+  # ----------------------------------------------------
+  # JOB 3: Run Report Script + Commit Output
+  # ----------------------------------------------------
   run-and-commit:
+    needs: push-docker
     runs-on: ubuntu-latest
-    needs: build-and-push
 
     steps:
-      - name: Checkout repo
+      - name: Checkout Repository
         uses: actions/checkout@v4
 
-      # ------------------------------
-      # RUN CONTAINER
-      # ------------------------------
-      - name: Run report generator container
-        run: |
-          docker run --rm \
-            -v ${{ github.workspace }}:/app/output \
-            ${{ secrets.DOCKER_USERNAME }}/daily-report:latest
+      - name: Make Report Script Executable
+        run: chmod +x script/daily_report.sh
 
-      # ------------------------------
-      # COMMIT REPORT
-      # ------------------------------
-      - name: Commit daily report
+      - name: Run Report Script
+        run: bash script/daily_report.sh
+
+      - name: Commit and Push Reports
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          git config --global user.email "github-actions[bot]@users.noreply.github.com"
-          git config --global user.name "github-actions[bot]"
-          git add .
-          git commit -m "Auto update: Daily system report $(date)" || echo "No changes to commit"
-          git push
+          git config user.name "github-actions[bot]"
+          git config user.email "github-actions[bot]@users.noreply.github.com"
+          git add reports/ || true
+          git commit -m "Daily Report: $(date +'%Y-%m-%d')" || echo "No changes"
+          git push origin main
+
+      - name: Upload Report Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: system-report
+          path: reports/
